export * from './user.service'
export * from './config'
export * from './usuario.service'
export * from './pelotao.service'
export * from './oficial.service'
export * from './escala.service'
export * from './atirador.service'
